@startuml
package system as "UniVacinas" {
	package cloud as "Serviço Cloud" {

		together {
			package presentationView as "Visão" {
				package client as "Visão Cliente" {
				}
				package employee as "Visão Funcionário" {
				}
			}
			package interface as "Aplicação" {
				package mobile as "APP" {
				}
				package web as "Website" {
				}
				package desktop as "AppDesktop" {
				}
			}

		}
		package internalSystem as "Sistema interno" {
			package domain as "Domínio" {
				package vaccine as "Vacina" {
				}
				package user as "Usuário" {
				}
				package storage as "Estoque" {
				}
				package service as "Atendimento" {
				}
				package purchase as "Compra" {
				}
			}
			together {
				package crosscuttingClient as "ConexaoServidor" {
				}
				package crosscuttingDatabase as "ConexaoBancoDeDados" {
				}
			}
		}
		package database as "Banco de dados" {
		}

	}
	package   externalServices as  "Serviços terceiros" {
		package  payment  as "Sistema de Pagamentos" {
		}
		package  sipni  as "Sistema SI-PNI" {
		}
		package  suppliers  as "Sistema de Fornecedores" {
		}
		package  convenants as  "Sistema de Convênios" {
		}
		package  auth as  "Autenticação" {
		}
	}
}


domain -[hidden]-> crosscuttingDatabase
internalSystem -[hidden]-> database
cloud -[hidden]-> externalServices

interface -> presentationView
interface -> internalSystem
crosscuttingDatabase -> database
crosscuttingClient -> externalServices

@enduml