@startuml

interface "REST API" as restApiAplicacaoInterna
interface "MQTT API" as mqttApiAplicacaoInterna
interface "REST API" as restApiAplicacaoExterna
interface "Persistência" as interfacePersistencia

database bancoDeDados as "Banco de Dados Corporativo" {
    component sistemaGerenciamento as "Sistema Gerenciamento Banco de Dados"
}

sistemaGerenciamento - interfacePersistencia

node clienteWeb as "Cliente Externo Web" {
    component clientViewWeb as "Visão Cliente Web"
}

node clienteMobile as "Cliente Externo Mobile" {
    component clientViewApp as "Visão Cliente App"
}

node servidorExterno as "Servidor Aplicação Externa" {
    component aplicacaoExterna as "Aplicação Externa" {
        component moduloCliente as "Cliente"
    }
}

restApiAplicacaoExterna - aplicacaoExterna
clientViewWeb --> restApiAplicacaoExterna : HTTP
clientViewApp --> restApiAplicacaoExterna : HTTP

node dispositivoMonitoramento as "Dispositivo Monitoramento" {
    component interfaceIOT as "Interface IOT"
}

node dispositivoFuncionario as "Dispositivo Funcionário" {
    component viewFuncionario as "Visão Funcionário"
}

node servidorInterno as "Servidor Aplicação Interna" {
    component aplicacaoInterna as "Aplicação Interna" {
        component moduloAtendimento as "Atendimento"
        component moduloVacina as "Vacina"
        component moduloEstoque as "Estoque"
        component moduloCompra as "Compra"
        component moduloUsuario as "Usuario"
    }
}

mqttApiAplicacaoInterna -- aplicacaoInterna
restApiAplicacaoInterna -- aplicacaoInterna

aplicacaoInterna -> interfacePersistencia : ODBC
aplicacaoExterna --> restApiAplicacaoInterna : HTTP
viewFuncionario --> restApiAplicacaoInterna : HTTP
interfaceIOT --> mqttApiAplicacaoInterna : MQTT

interface "REST API" as restApiAplicacaoPagamento
node servicoPagamento as "Servidor Serviço de Pagamentos" {
    component aplicacaoPagamento as "Aplicação Pagamentos"
}
aplicacaoPagamento -- restApiAplicacaoPagamento

interface "REST API" as restApiAplicacaoSIPNI
node servicoSIPNI as "Servidor Serviço SI-PNI" {
    component aplicacaoSIPNI as "Aplicação SI-PNI"
}
aplicacaoSIPNI -- restApiAplicacaoSIPNI

interface "REST API" as restApiAplicacaoFornecedores
node servicoFornecedores as "Servidor Serviço de Fornecedores" {
    component aplicacaoFornecedores as "Aplicação Fornecedores"
}
aplicacaoFornecedores -- restApiAplicacaoFornecedores

interface "REST API" as restApiAplicacaoConvenios
node servicoConvenios as "Servidor Serviço de Convênios" {
    component aplicacaoConvenios as "Aplicação Convênios"
}
aplicacaoConvenios -- restApiAplicacaoConvenios

interface "REST API" as restApiAplicacaoAutenticacao
node servicoAutenticacao as "Servidor Serviço de Autenticação" {
    component aplicacaoAutenticacao as "Aplicação Autenticação Google"
}
aplicacaoAutenticacao -- restApiAplicacaoAutenticacao

aplicacaoInterna ---> restApiAplicacaoConvenios : HTTP
aplicacaoInterna ---> restApiAplicacaoAutenticacao : HTTP
aplicacaoInterna ---> restApiAplicacaoFornecedores : HTTP
aplicacaoInterna ---> restApiAplicacaoPagamento : HTTP
aplicacaoInterna ---> restApiAplicacaoSIPNI : HTTP



@enduml
