@startuml
package system as "UNIVACINAS" {
        package view as "VIEW" {
	        package externalClientWeb as "Cliente Externo WEB" {
                        package webClientVision as "Visão Cliente WEB" {
                        }
                }
	        package externalClientMobile as "Cliente Externo Mobile" {
                        package appClientVision as "Visão Cliente Mobile" {
                        }
                }
	        package employeeDevice as "Dispositivo Funcionário" {
                        package employeeVision as "Visão Funcionário" {
                        }
                }
	        package monitoringDevice as "Dispositivo de Monitoramento" {
                        package monitoringDeviceVision as "Interface IoT" {
                        }
                }
        }
        package presentation as "PRESENTATION" {
                package externalServer as "Servidor Aplicação Externa" {
                        package externalApplicationWrapper as "APPLICATION" {
                                package externalApplication as "Aplicação Externa" {
                                        package domain as "DOMAIN" {
                                                package client as "Cliente" {
                                                }
                                        }
                                }
                        }
                }
                package internalServer as "Servidor Aplicação Interna" {
                        package internalApplicationWrapper as "APPLICATION" {
                                package internalApplication as "Aplicação Interna" {
                                        package domain as "DOMAIN" {
                                                package client as "Atendimento" {
                                                }
                                                package client as "Vacina" {
                                                }
                                                package client as "Estoque" {
                                                }
                                                package client as "Compra" {
                                                }
                                                package client as "Usuário" {
                                                }
                                        }
                                }
                        }
                }
                package thirdPartyServer as "Serviços Terceiros" {
                        together {
                                package paymentServer as "Servidor Serviço de Pagamentos" {
                                        package paymentApplication as "Aplicação Pagamentos" {
                                        }
                                }
                                package sipniServer as "Servidor Serviço SI-PNI" {
                                        package sipniApplication as "Aplicação SI-PNI" {
                                        }
                                }
                                package suppliersServer as "Servidor Serviço de Fornecedores" {
                                        package suppliersApplication as "Aplicação Fornecedores" {
                                        }
                                }
                        }
                        together {
                                package covenantsServer as "Servidor Serviço de Convênios" {
                                        package covenantsApplication as "Aplicação Convênios" {
                                        }
                                }
                                package authServer as "Servidor Serviço de Autenticação" {
                                        package authApplication as "Aplicação Autenticação Google" {
                                        }
                                }
                        }
                }
        }
        package database as "Banco de Dados Corporativo" {
        }
}

paymentServer -[hidden]-> covenantsServer
internalServer -[hidden]-> thirdPartyServer
view -[hidden]-> presentation

webClientVision -> externalApplication
appClientVision -> externalApplication
externalApplication -> internalApplication
employeeVision -> internalApplication
monitoringDeviceVision -> internalApplication
internalApplication -> database
internalApplication -> paymentApplication
internalApplication -> sipniApplication
internalApplication -> suppliersApplication
internalApplication -> covenantsApplication
internalApplication -> authApplication

@enduml